const assets=[
 {name:'api-gateway-01',ip:'10.20.1.11',env:'生产',type:'容器节点',owner:'陈宇',status:'正常',check:'2 分钟前',service:'API Gateway'},
 {name:'order-service-02',ip:'10.20.1.24',env:'生产',type:'应用服务',owner:'林睿',status:'告警',check:'5 分钟前',service:'Order Service'},
 {name:'mysql-primary-01',ip:'10.20.2.10',env:'生产',type:'数据库',owner:'周明',status:'正常',check:'刚刚',service:'MySQL Primary'},
 {name:'redis-cache-01',ip:'10.20.2.31',env:'生产',type:'缓存服务',owner:'陈宇',status:'正常',check:'1 分钟前',service:'Redis Cache'},
 {name:'web-portal-staging',ip:'10.30.1.18',env:'测试',type:'Web 服务',owner:'孙宁',status:'注意',check:'8 分钟前',service:'Web Portal'},
 {name:'monitor-agent-01',ip:'10.20.3.8',env:'生产',type:'监控节点',owner:'陈宇',status:'正常',check:'刚刚',service:'Monitor Agent'}
];
let alerts=[
 {id:1,level:'critical',title:'order-service-02 CPU 使用率持续过高',detail:'当前使用率 92%，已超过 85% 阈值并持续 15 分钟。',asset:'order-service-02',time:'12 分钟前'},
 {id:2,level:'warning',title:'web-portal-staging SSL 证书即将过期',detail:'证书将在 7 天后失效，请安排续期。',asset:'web-portal-staging',time:'38 分钟前'},
 {id:3,level:'info',title:'api-gateway-01 检测到配置变更',detail:'负载均衡路由规则已被更新。',asset:'api-gateway-01',time:'1 小时前'}
];
const tasks=[['◌','主机连通性检测','验证目标主机网络连通与延迟'],['▤','磁盘空间巡检','检查所有挂载点的剩余容量'],['⌁','服务端口检测','验证关键服务端口监听状态'],['⌁','HTTP 健康检查','请求服务健康检查端点'],['◇','SSL 证书检测','检查证书有效期与签发状态']];
const records=[['主机连通性检测','生产环境 · 24 个目标','成功','10:24:18'],['磁盘空间巡检','生产环境 · 24 个目标','成功','10:00:03'],['HTTP 健康检查','生产环境 · 12 个端点','异常','09:35:42'],['SSL 证书检测','生产环境 · 8 个域名','成功','09:00:08']];
const audit=[['陈宇','执行了全量主机连通性检测','10:24:18'],['系统','自动关闭了 api-gateway-02 的高延迟告警','10:18:02'],['林睿','将告警 #AL-2901 指派给 陈宇','09:58:41'],['陈宇','更新资产 redis-cache-01 的负责人','昨天 18:33'],['系统','完成每日 SSL 证书检测','昨天 09:00']];
const $=s=>document.querySelector(s);const esc=s=>s.replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function statusClass(s){return s==='正常'?'ok':s==='注意'?'warn':'down'}
function renderAssets(filter=''){ $('#asset-body').innerHTML=assets.filter(a=>Object.values(a).join(' ').toLowerCase().includes(filter.toLowerCase())).map(a=>`<tr><td class="asset-name">${a.name}<small>${a.service}</small></td><td class="mono">${a.ip}</td><td><span class="env ${a.env==='测试'?'test':''}">${a.env}环境</span></td><td>${a.type}</td><td>${a.owner}</td><td><span class="status ${statusClass(a.status)}">${a.status}</span></td><td>${a.check}</td><td><button class="row-menu">⋮</button></td></tr>`).join('') }
function renderAlerts(){const compact=alerts.slice(0,3).map(a=>`<div class="alert-row"><span class="severity ${a.level}"></span><div><strong>${a.title}</strong><small>${a.asset}</small></div><time class="alert-time">${a.time}</time></div>`).join('');$('#dashboard-alerts').innerHTML=compact; $('#alert-list').innerHTML=alerts.map(a=>`<div class="alert-full"><span class="severity ${a.level}"></span><div><strong>${a.title}</strong><p>${a.detail} · ${a.asset} · ${a.time}</p></div><div class="alert-actions"><button class="secondary" onclick="ackAlert(${a.id})">确认告警</button><button class="primary" onclick="closeAlert(${a.id})">关闭告警</button></div></div>`).join('')||'<div class="empty">当前没有待处理告警，环境很安静。</div>';$('#alert-count').textContent=alerts.length;$('#all-alert-count').textContent=alerts.length}
function renderServices(){$('#service-list').innerHTML=assets.slice(0,5).map(a=>`<div class="service-row"><span class="service-dot" style="background:${a.status==='正常'?'#23b28a':a.status==='注意'?'#e4a13a':'#df5961'}"></span><div><b>${a.service}</b><small>${a.ip}</small></div><span class="badge ${a.status==='正常'?'ok':'warn'}">${a.status==='正常'?'正常':'需关注'}</span></div>`).join('')}
function renderChecks(){const html=records.slice(0,3).map(r=>`<div class="recent-item"><span class="check-status">✓</span><div><b>${r[0]}</b><small>${r[1]}</small></div><time>${r[3]}</time></div>`).join('');$('#recent-checks').innerHTML=html;$('#check-cards').innerHTML=tasks.map(t=>`<div class="check-card"><span class="task-icon">${t[0]}</span><div><b>${t[1]}</b><p>${t[2]}</p></div><button class="run" data-run="${t[1]}">运行</button></div>`).join('');$('#execution-list').innerHTML=records.map(r=>`<div class="execution-item"><span class="check-status">${r[2]==='异常'?'!':'✓'}</span><div><b>${r[0]}</b><p>${r[1]}</p><time>${r[3]}</time></div><span class="badge ${r[2]==='成功'?'ok':'warn'}">${r[2]}</span></div>`).join('')}
function renderAudit(){$('#audit-list').innerHTML=audit.map(a=>`<div class="audit-item"><span class="audit-symbol">⌁</span><div><b>${a[0]}</b><p>${a[1]}</p></div><time>${a[2]}</time></div>`).join('')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function startTask(name){toast(`正在执行「${name}」...`);setTimeout(()=>{records.unshift([name,'生产环境 · 自动检测','成功',new Date().toLocaleTimeString('zh-CN',{hour12:false})]);records.pop();renderChecks();$('#updated-at').textContent='刚刚';toast(`「${name}」已完成，所有目标正常`)},1200)}
window.closeAlert=id=>{alerts=alerts.filter(a=>a.id!==id);renderAlerts();audit.unshift(['陈宇',`关闭了告警 #AL-${2900+id}`,new Date().toLocaleTimeString('zh-CN',{hour12:false})]);renderAudit();toast('告警已关闭并记录到审计日志')};window.ackAlert=id=>{toast(`告警 #AL-${2900+id} 已确认，等待处理`) };
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');const labels={dashboard:['控制台','运行总览'],assets:['资源中心','资产管理'],checks:['作业中心','巡检中心'],alerts:['事件中心','告警中心'],audit:['合规中心','审计日志']};$('#page-kicker').textContent=labels[b.dataset.view][0];$('#page-title').textContent=labels[b.dataset.view][1]});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>document.querySelector(`[data-view="${b.dataset.go}"]`).click());$('#asset-search').oninput=e=>renderAssets(e.target.value);$('#run-all').onclick=()=>startTask('全量巡检');$('#add-asset').onclick=()=>$('#asset-modal').classList.add('show');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.remove('show'));$('#save-asset').onclick=()=>toast('资产已保存，等待首次巡检');$('#new-check').onclick=()=>toast('已创建一份新的空白巡检任务');document.addEventListener('click',e=>{if(e.target.matches('[data-run]'))startTask(e.target.dataset.run)});function updateClock(){$('#clock').textContent=new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())+' CST'}setInterval(updateClock,1000);updateClock();renderAssets();renderAlerts();renderServices();renderChecks();renderAudit();
